-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKuWxYB2mDVpMkajp
GgPnuVWcXbwD5ZWpF1lGI3/sMJGgCgYIKoZIzj0DAQehRANCAAT0cjvbhxfYcLEp
TUvzdh0dbLFFoCK2m6Dw3Ll8yzqVZd473JsmrcD7KStFgsxcw2im5HCdsCCkieiH
v+6Mju3E
-----END PRIVATE KEY-----